<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js([
    pi::url('static/js/html5shiv.js')   => [
        'conditional' => 'lt IE 9',
    ],
    pi::url('static/js/respond.min.js') => [
        'conditional' => 'lt IE 9',
    ],
]);

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap([
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css',
]);

// Load front.css
$this->css($this->assetTheme('css/front.css'));
$this->css($this->assetTheme('css/animate.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink([
    'rel'  => 'apple-touch-icon',
    'href' => $this->assetTheme('image/touch-icon-iphone.png'),
]);
// Apple icon for ipad
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png'),
]);
// Apple icon for iphone retina
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png'),
]);
// Apple icon for ipad retina
$this->headLink([
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png'),
]);

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink([
    'rel'  => 'shortcut icon',
    'type' => 'image/x-icon',
    'href' => $this->favicon(),
]);
$this->headLink([
    'rel'  => 'shortcut icon',
    'type' => 'image/png',
    'href' => $this->favicon('favicon.png'),
]);

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks        = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    ['prefix' => [
        [
            'label' => __('Home'),
            'href'  => Pi::url($this->url('home')),
        ],
    ]]
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <div class="pi-header-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="clearfix">
                        <ul class="nav navbar-nav  pi-header-phone">
                            <li>
                                <a href="<?php echo Pi::url($this->url('home')); ?>/contact" title="تلفن">
                                    <i class="fa fa-phone"></i>021-22140563
                                </a>
                            </li>
                        </ul>
                        <?php //echo $this->widget('system-user-bar'); ?>
                    </div>
                    <div class="clearfix">
                        <nav class="navbar navbar-inverse">
                            <div class="navbar-header">
                                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <i class="fa fa-bars"></i>
                                </button>
                            </div>
                            <div class="navbar-collapse collapse">
                                <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                            </div>
                        </nav>
                    </div>
                </div>
                <div class="col-md-4 text-right">
                    <?php if ($module == 'system') { ?>
                        <h1>
                            <a href="<?php echo Pi::url($this->url('home')); ?>"
                               title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>"
                                     alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2>
                            <a href="<?php echo Pi::url($this->url('home')); ?>"
                               title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>"
                                     alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h2>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>

    <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
    <?php } ?>
</header>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<section class="pi-section">
    <div class="container-fluid">
        <div class="pi-main-container">
            <?php if ($breadcrumbs) {
                echo $breadcrumbs;
            } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <!-- Top head zone -->

            <div class="row">
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-md-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" data-ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(['options' => ['type' => 'js']]); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Center bottom zone -->
                    <?php if (isset($blocks['7'])) { ?>
                        <div class="pi-zone-7">
                            <?php foreach ($blocks['7'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-md-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Bottom foot zone -->
            <?php if (isset($blocks['99'])) { ?>
                <div class="pi-zone-99">
                    <?php foreach ($blocks['99'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</section>
<?php if ($module == 'system') { ?>
    <section class="pi-section-map clearfix">
        <div class="pi-section-map-address">
            <address>
                <ul class="list-inline">
                    <li><strong> آدرس : </strong>تهران -سعادت اباد-ميدان فرهنگ-خيابان معارف-ساختمان كيميا -طبقه اول</li>
                </ul>
                <ul class="list-inline">
                    <li><strong> تلفن : </strong></li>
                    <li>021-22140563</li>
                </ul>
            </address>
        </div>
        <?php $locations = [
            'latitude'  => '35.782005',
            'longitude' => '51.385117',
            'zoom'      => 16,
            'title'     => _escape($sitename),
        ]; ?>
        <?php echo $this->googleMap($locations, 'AIzaSyC9_S2FuQafjyYzxozfDDwIpxE8y7S_48g'); ?>
    </section>
<?php } ?>
<!-- Footer: sitelink -->
<footer class="pi-footer clearfix">
    <div class="pi-footer-body clearfix">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-5 col-xs-12">
                    <h4>پلاسما درمان فارمد</h4>
                    <p>با توجه به شيوع بيماريهاي عفوني و قابل انتقال از طريق خون و در راستاي سياست هاي اصولي سازمان انتقال خون ايران و مجامع بهداشتي بين المللي و همچنين حجم بالاي اهداي داوطلبانه خون و تعداد زياد بيماران مصرف كننده مشتقات مستخرجه از پلاسما و با اخذ مجوزات لازم از سازمان غذا و دارو شركت پلاسما درمان فارمد -سهامي عام در تاريخ ٩٦/٤/٢١ ثبت گريده است.</p>
                </div>
                <div class="col-md-2 col-xs-12">
                    <h4>اطلاعات وب سایت</h4>
                    <ul class="list-unstyled">
                        <li><a title="پرسش های متداول" href="<?php echo Pi::url($this->url('home')); ?>/page/faq">پرسش های متداول</a></li>
                        <li><a title="قوانین و مقررات" href="<?php echo Pi::url($this->url('home')); ?>/page/terms-and-conditions">قوانین و مقررات</a></li>
                        <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>/page/about-us">درباره ما</a></li>
                        <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>/contact">تماس با ما</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-xs-12">
                    <h4>محصولات</h4>
                    <ul class="list-unstyled"></ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <div class="pi-footer-logo">
                        <ul class="list-inline">
                            <li>
                                <img class="img-responsive"
                                     src="<?php echo $this->assetTheme('image/behpardakht.png'); ?>" alt="به پرداخت">
                            </li>
                            <li>
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/enamad.png'); ?>"
                                     alt="نماد اعتماد الکترونیک">
                            </li>
                        </ul>
                    </div>
                    <div class="pi-footer-social">
                        <p>شبکه های اجتماعی</p>
                        <ul class="list-inline">
                            <li><a target="_blank" title="اینستاگرام" href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a target="_blank" title="فیسبوک" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a target="_blank" title="لینکداین" href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a target="_blank" title="تلگرام" href="#"><i class="fa fa-telegram"></i></a></li>
                            <li><a target="_blank" title="توییتر" href="#"><i class="fa fa-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright clearfix">
        <div class="container-fluid">
            <div class="row">
                <div class="text-left col-md-6 col-xs-12" data-rel="license"> تمام حقوق مطالب برای وب سایت <a
                            title="<?php echo _escape($sitename); ?>"
                            href="<?php echo Pi::url($this->url('home')); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.
                </div>
                <div class="text-right col-md-6 col-xs-12" data-rel="license"> توسعه <a title="فراگسترش"
                                                                                        href="http://www.faragostaresh.com"
                                                                                        target="_blank">فراگسترش</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->conditions() ?>
</body>
</html>