<div class="event-block clearfix">
    <div class="recent-event-list clearfix">
        <?php $this->jQuery(array(
                'extension/owl.carousel.min.js',
                'extension/owl.carousel.css',
         )); ?>
        <div class="owl-carousel clearfix">
            <?php foreach ($block['resources'] as $event) { ?>
                <?php $thumbUrl = Pi::api('doc','media')->getSingleLinkUrl($event['main_image'])->setConfigModule('news')->thumb('thumbnail'); ?>
                <?php $mediumUrl = Pi::api('doc','media')->getSingleLinkUrl($event['main_image'])->setConfigModule('news')->thumb('medium'); ?>
                <div class="item" itemscope
                     itemtype="https://schema.org/Event">
                    <a itemprop="url" class="u-url hover-caption-more"
                       title="<?php echo $this->escape($event['title']); ?>"
                       href="<?php echo $this->escape($event['eventUrl']); ?>">
                        <img itemprop="image" class="media-object img-responsive u-photo"
                             src="<?php echo $this->escape($thumbUrl); ?>"
                             alt="<?php echo $this->escape($event['title']); ?>">
                    </a>
                    <h3 itemprop="name headline">
                        <a itemprop="url" class="u-url hover-caption-more"
                           title="<?php echo $this->escape($event['title']); ?>"
                           href="<?php echo $this->escape($event['storyUrl']); ?>">
                            <?php echo $this->escape($event['title']); ?>
                        </a>
                    </h3>
                    <?php if (!empty($event['text_summary']) && $block['show-summary']) { ?>
                        <div class="clearfix">
                            <div class="event-single-summery p-summary" itemprop="description">
                                <?php echo $event['text_summary']; ?>
                            </div>
                        </div>
                    <?php } elseif (!empty($event['text_summary'])) { ?>
                        <meta itemprop="description" content="<?php echo $this->escape($event['text_summary']); ?>" />
                    <?php } ?>
                    <?php if (!empty($event['time_start']) && !empty($event['time_end'])) { ?>
                        <meta itemprop="startDate" content="<?php echo $this->escape(date("Y-m-d H:i:s", $event['time_start'])); ?>" />
                        <meta itemprop="endDate" content="<?php echo $this->escape(date("Y-m-d H:i:s", $event['time_end'])); ?>" />
                    <?php } elseif (!empty($event['time_start'])) { ?>
                        <meta itemprop="startDate" content="<?php echo $this->escape(date("Y-m-d H:i:s", $event['time_start'])); ?>" />
                    <?php } ?>
                    <meta itemprop="priceCurrency" content="<?php echo $this->escape($event['price_currency']); ?>" />
                </div>
            <?php } ?>
        </div>
    </div>
</div>